# Download test data from: https://osf.io/8jz7e/
model_path: /home/borismeinardus/Aneurysm-Detection/CHECKPOINT_DIR_1/best_checkpoint.pytorch
model:
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 32 # [32, 64, 128, 256]
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
  # if True applies the final normalization layer (sigmoid or softmax), otherwise the networks returns the output from the final convolution layer; use False for regression problems, e.g. de-noising
  is_segmentation: true
predictor:
  name: 'StandardPredictor'
loaders:
  # save predictions to output_dir
  output_dir: /home/borismeinardus/Aneurysm-Detection/data/predictions/iteration1/
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 1
  # mirror pad the raw data in each axis for sharper prediction near the boundaries of the volume
  mirror_padding: [16, 32, 32]
  # how many subprocesses to use for data loading
  num_workers: 8
  # test loaders configuration
  test:
    file_paths:
      # - /home/borismeinardus/Aneurysm-Detection/data/h5/exam_test_set
      - /home/borismeinardus/Aneurysm-Detection/data/h5/testing

    slice_builder:
      name: SliceBuilder
      patch_shape: [200, 220, 220]
      stride_shape: [50, 60, 60]


    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
